[tool.poetry]
name = "nonebot_plugin_web_bottle"
version = "0.0.1"
description = "Web Bottle post plugin in Nonebot"
authors = ["Xican <723926109@qq.com>"]
license = "GNU GPLv3"
readme = "README.md"
homepage = "https://github.com/luosheng520qaq/nonebot-plugin-web-bottle/"
repository = "https://github.com/luosheng520qaq/nonebot-plugin-web-bottle/"

[tool.poetry.dependencies]
python = "^3.11"
nonebot2 = {extras = ["fastapi"], version = "^2.0.0"}
aiofiles = ">=0.8.0"
nonebot_plugin_localstore = ">=0.7.0"
httpx = ">=0.23.0"
fastapi = ">=0.110.0"
pydantic = ">=1.10.11"

[tool.pdm.dev-dependencies]
dev = [
    "nonebot2[fastapi,uvicorn]>=2.3.2",
    "nonebot-adapter-onebot>=2.4.4",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "nonebot-plugin-web-bottle"
version = "0.0.1"
description = "有web的漂流瓶"
authors = [
    {name = "Xican", email = "723926109@qq.com"},
]
dependencies = [
    ""
    "fastapi>=0.110.0",
    "aiofiles>=23.2.1",
    "httpx>=0.23.0",
    "pydantic>=1.10.11",
    "nonebot_plugin_localstore>=0.7.0",
]

requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/luosheng520qaq/nonebot-plugin-web-bottle/"
repository = "https://github.com/luosheng520qaq/nonebot-plugin-web-bottle/"
